<?php
/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

use Thrift\Type\TType;


/**
 * The first thing to know about are types. The available types in Thrift are:
 * 
 *  bool        Boolean, one byte
 *  byte        Signed byte
 *  i16         Signed 16-bit integer
 *  i32         Signed 32-bit integer
 *  i64         Signed 64-bit integer
 *  double      64-bit floating point value
 *  string      String
 *  binary      Blob (byte array)
 *  map<t1,t2>  Map from one type to another
 *  list<t1>    Ordered list of one type
 *  set<t1>     Set of unique elements of one type
 * 
 * Did you also notice that Thrift supports C style comments?
 */

class TChatAuditMsg {
  static $_TSPEC;

  /**
   * @var int
   */
  public $srcUId = null;
  /**
   * @var int
   */
  public $dstUId = null;
  /**
   * @var int
   */
  public $msgType = null;
  /**
   * @var string
   */
  public $content = null;
  /**
   * @var int
   */
  public $groupId = null;
  /**
   * @var int
   */
  public $msgId = null;
  /**
   * @var int
   */
  public $mastermsgId = null;
  /**
   * @var int
   */
  public $notifyType = null;
  /**
   * @var int
   */
  public $updateId = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'srcUId',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'dstUId',
          'type' => TType::I32,
          ),
        3 => array(
          'var' => 'msgType',
          'type' => TType::BYTE,
          ),
        4 => array(
          'var' => 'content',
          'type' => TType::STRING,
          ),
        5 => array(
          'var' => 'groupId',
          'type' => TType::I32,
          ),
        6 => array(
          'var' => 'msgId',
          'type' => TType::I32,
          ),
        7 => array(
          'var' => 'mastermsgId',
          'type' => TType::I32,
          ),
        8 => array(
          'var' => 'notifyType',
          'type' => TType::I32,
          ),
        9 => array(
          'var' => 'updateId',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['srcUId'])) {
        $this->srcUId = $vals['srcUId'];
      }
      if (isset($vals['dstUId'])) {
        $this->dstUId = $vals['dstUId'];
      }
      if (isset($vals['msgType'])) {
        $this->msgType = $vals['msgType'];
      }
      if (isset($vals['content'])) {
        $this->content = $vals['content'];
      }
      if (isset($vals['groupId'])) {
        $this->groupId = $vals['groupId'];
      }
      if (isset($vals['msgId'])) {
        $this->msgId = $vals['msgId'];
      }
      if (isset($vals['mastermsgId'])) {
        $this->mastermsgId = $vals['mastermsgId'];
      }
      if (isset($vals['notifyType'])) {
        $this->notifyType = $vals['notifyType'];
      }
      if (isset($vals['updateId'])) {
        $this->updateId = $vals['updateId'];
      }
    }
  }

  public function getName() {
    return 'TChatAuditMsg';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->srcUId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->dstUId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::BYTE) {
            $xfer += $input->readByte($this->msgType);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->content);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->groupId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 6:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->msgId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 7:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->mastermsgId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 8:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->notifyType);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 9:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->updateId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('TChatAuditMsg');
    if ($this->srcUId !== null) {
      $xfer += $output->writeFieldBegin('srcUId', TType::I32, 1);
      $xfer += $output->writeI32($this->srcUId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->dstUId !== null) {
      $xfer += $output->writeFieldBegin('dstUId', TType::I32, 2);
      $xfer += $output->writeI32($this->dstUId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->msgType !== null) {
      $xfer += $output->writeFieldBegin('msgType', TType::BYTE, 3);
      $xfer += $output->writeByte($this->msgType);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->content !== null) {
      $xfer += $output->writeFieldBegin('content', TType::STRING, 4);
      $xfer += $output->writeString($this->content);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->groupId !== null) {
      $xfer += $output->writeFieldBegin('groupId', TType::I32, 5);
      $xfer += $output->writeI32($this->groupId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->msgId !== null) {
      $xfer += $output->writeFieldBegin('msgId', TType::I32, 6);
      $xfer += $output->writeI32($this->msgId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->mastermsgId !== null) {
      $xfer += $output->writeFieldBegin('mastermsgId', TType::I32, 7);
      $xfer += $output->writeI32($this->mastermsgId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->notifyType !== null) {
      $xfer += $output->writeFieldBegin('notifyType', TType::I32, 8);
      $xfer += $output->writeI32($this->notifyType);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->updateId !== null) {
      $xfer += $output->writeFieldBegin('updateId', TType::I32, 9);
      $xfer += $output->writeI32($this->updateId);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}




